version: "3.9"
services:
  local_network:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: local_network_run
    init: true
    working_dir: /code
    entrypoint: [ "./docker/run_setup.sh" ]
    command: ["set -a", "source vars.sh"]
    network_mode: "host"
    volumes:
      - type: bind
        source: ../
        target: /code/
  relayer:
    image: avaplatform/awm-relayer:v0.2.0
    container_name: relayer_run
    init: true
    working_dir: /code
    entrypoint: ./docker/run_relayer.sh
    network_mode: "host"
    user: "root"
    volumes:
      - type: bind
        source: ../
        target: /code/
